# This rule is not used by the project arks-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over arks.scitix.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: arks-operator
    app.kubernetes.io/managed-by: kustomize
  name: arksapplication-admin-role
rules:
- apiGroups:
  - arks.scitix.ai
  resources:
  - arksapplications
  verbs:
  - '*'
- apiGroups:
  - arks.scitix.ai
  resources:
  - arksapplications/status
  verbs:
  - get
