# This rule is not used by the project arks-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to arks.scitix.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: arks-operator
    app.kubernetes.io/managed-by: kustomize
  name: arksendpoint-viewer-role
rules:
- apiGroups:
  - arks.scitix.ai
  resources:
  - arksendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arks.scitix.ai
  resources:
  - arksendpoints/status
  verbs:
  - get
